# Generated by Django 5.2.3 on 2025-07-22 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderitem_delete_orderitems'),
        ('vendor', '0003_vendor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='vendor.vendor'),
        ),
    ]
