# Generated by Django 5.2.3 on 2025-06-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateField(null=True, verbose_name='D.O.B'),
        ),
    ]
