# Generated by Django 5.2.3 on 2025-07-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email'),
        ('user', '0005_address_phone_user_phone'),
    ]

    operations = [
    ]
